app = "dental-diagnostic-system-main"
primary_region = "fra"

[build]
  # Use the python buildpack explicitly
  buildpacks = ["paketo-buildpacks/python"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
